hmrc/external-guidance

- app/models/PublishedProcess.scala
- app/repositories/PublishedRepository.scala
- app/repositories/formatters/PublishedProcessFormatter.scala
- test/repositories/formatters/PublishedProcessFormatterSpec.scala
Note the test coverage is currently below the limit for delivery. This should be fixed when the controller and service have been written and we can write some integration tests.
> EG-364 Published process repository and supporting classes

- app/controllers/PublishedController.scala
- app/models/errors/Error.scala
- app/repositories/PublishedRepository.scala
- app/services/PublishedService.scala
- app/utils/Validators.scala
- conf/app.routes
- it/endpoints/GetPublishedProcessISpec.scala
- test/controllers/PublishedControllerSpec.scala
- test/controllers/ScratchControllerSpec.scala
- test/mocks/MockPublishedRepository.scala
- test/mocks/MockPublishedService.scala
- test/services/PublishedServiceSpec.scala
- test/utils/ValidatorsSpec.scala
Create controller and service to enable external guidance to retrieve published processes.
> EG-363 Controller and service methods to retrieve published process

- README.md
- app/controllers/ApprovalController.scala
- app/models/ApprovalProcess.scala
- app/repositories/ApprovalRepository.scala
- app/repositories/PublishedRepository.scala
- app/repositories/ScratchRepository.scala
- app/repositories/formatters/ApprovalProcessFormatter.scala
- app/services/ApprovalService.scala
- conf/app.routes
- it/endpoints/GetApprovalProcessISpec.scala
- it/endpoints/PostApprovalProcessISpec.scala
- test/controllers/ApprovalControllerSpec.scala
- test/mocks/MockApprovalRepository.scala
- test/mocks/MockApprovalService.scala
- test/repositories/formatters/ApprovalProcessFormatterSpec.scala
- test/services/ApprovalServiceSpec.scala
Revised class names and end point for the approval process.
End points changed, so ManageFrontEnd will need to be updated
This pull request overrides the previous one (EG-255) which had unverified commits due to invalid local configuration when 1st few commits were done.  Easiest way to get round that was to create a new branch and apply changes again.
> EG-402 - Updated branch to handle the new Approval Process

- README.md
- app/controllers/ProcessReviewController.scala
- app/models/ApprovalProcessStatusChange.scala
- app/repositories/ApprovalRepository.scala
- app/services/ReviewService.scala
- conf/app.routes
- it/data/ExamplePayloads.scala
- it/endpoints/PostProcessReviewISpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/data/ReviewData.scala
- test/mocks/MockApprovalRepository.scala
- test/mocks/MockReviewService.scala
- test/models/ApprovalProcessJson.scala
- test/repositories/formatters/ApprovalProcessFormatterSpec.scala
- test/services/ReviewServiceSpec.scala
Updated PR to fix the issue with unverfied commits after deletion of GPG key
> EG-485 update endpoint

- app/controllers/ProcessReviewController.scala
- app/repositories/ApprovalProcessReviewRepository.scala
- app/services/ReviewService.scala
- conf/app.routes
- test/controllers/ProcessReviewControllerSpec.scala
- test/mocks/MockApprovalProcessReviewRepository.scala
- test/mocks/MockReviewService.scala
- test/services/ReviewServiceSpec.scala
End point for saving the fact check page review
> EG-556 fact check page update

- app/controllers/ProcessReviewController.scala
- conf/app.routes
- it/endpoints/GetProcessReviewISpec.scala
- it/endpoints/PostProcessReviewISpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
Needs to be merged at same time as manage-frontend and tests to ensure consistent URLs used
> Fix to url to remove the // and handle properly

- app/controllers/ProcessReviewController.scala
- app/models/errors/Error.scala
- app/services/ReviewService.scala
- conf/app.routes
- it/endpoints/PostProcessReviewISpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/mocks/MockReviewService.scala
- test/services/ReviewServiceSpec.scala
Works in conjunction with EG-606 on manage - must be merged 1st
> EG-607 - Determine if process has reviewed/checked all pages

- app/controllers/ProcessReviewController.scala
- app/models/ApprovalProcess.scala
- app/models/ApprovalProcessMeta.scala
- app/models/AuditInfo.scala
- app/repositories/formatters/ApprovalProcessMetaFormatter.scala
- app/services/ReviewService.scala
- it/endpoints/PostProcessReviewISpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/mocks/MockReviewService.scala
- test/models/ApprovalProcessJson.scala
- test/repositories/formatters/ApprovalProcessMetaFormatterSpec.scala
- test/services/ReviewServiceSpec.scala
Needs to be deployed in conjunction with same PR on manage frontend
> EG-627 EG-626 EG-619 2i Complete/Fact Check Complete/Published Audit Events

- app/config/AppConfig.scala
- app/config/Module.scala
- app/controllers/ApprovalController.scala
- app/controllers/actions/AuthenticatedIdentifierAction.scala
- app/models/requests/IdentifierRequest.scala
- conf/application.conf
- it/endpoints/GetApprovalProcessISpec.scala
- it/endpoints/PostProcessReviewISpec.scala
- it/stubs/AuthStub.scala
- test/base/ControllerBaseSpec.scala
- test/controllers/ApprovalControllerSpec.scala
- test/controllers/actions/AuthenticatedIdentifierActionSpec.scala
- test/controllers/actions/FakeIdentifierAction.scala
- test/mocks/MockAppConfig.scala
- test/mocks/MockAuthConnector.scala
This request needs to be merge to enable work to start on EG-681 and EG-682.
> EG-680 Add protection to /approval end point

- app/controllers/ApprovalController.scala
- app/controllers/ProcessReviewController.scala
- app/models/ApprovalProcessMeta.scala
- app/models/ApprovalProcessSummary.scala
- app/repositories/ApprovalRepository.scala
- app/repositories/formatters/ApprovalProcessMetaFormatter.scala
- app/services/ApprovalService.scala
- app/services/ReviewService.scala
- app/utils/Constants.scala
- conf/app.routes
- it/data/ExamplePayloads.scala
- it/endpoints/GetApprovalProcessISpec.scala
- it/endpoints/GetProcessReviewISpec.scala
- it/endpoints/PostApprovalProcessISpec.scala
- it/endpoints/PostProcessReviewISpec.scala
- test/controllers/ApprovalControllerSpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/mocks/MockApprovalService.scala
- test/mocks/MockReviewService.scala
- test/models/ApprovalProcessJson.scala
- test/repositories/formatters/ApprovalProcessMetaFormatterSpec.scala
- test/services/ApprovalServiceSpec.scala
- test/services/ReviewServiceSpec.scala
adding "In Progress" status and reviewType to the syummary data to enable better reporting/filtering on UI
> EG-758 - Partial review Status

- app/controllers/ApprovalController.scala
- app/controllers/actions/AuthenticatedIdentifierAction.scala
- app/controllers/actions/FactCheckerIdentifierAction.scala
- app/controllers/actions/TwoEyeReviewerAuthenticatedIdentifierAction.scala
- app/models/SummaryListCriteria.scala
- app/repositories/ApprovalRepository.scala
- app/services/ApprovalService.scala
- it/endpoints/PostProcessReviewISpec.scala
- it/stubs/AuthStub.scala
- test/controllers/ApprovalControllerSpec.scala
- test/controllers/actions/AuthenticatedIdentifierActionSpec.scala
- test/controllers/actions/FactCheckerAuthenticatedIdentifierActionSpec.scala
- test/controllers/actions/FakeFactCheckerIdentifierAction.scala
- test/controllers/actions/FakeIdentifierAction.scala
- test/controllers/actions/FakeTwoEyeReviewerIdentifierAction.scala
- test/controllers/actions/TwoEyeReviewerAuthenticatedIdentifierActionSpec.scala
- test/mocks/MockApprovalRepository.scala
- test/mocks/MockApprovalService.scala
- test/services/ApprovalServiceSpec.scala
Works with associated branch in manage-external-guidance-frontend
> EG-724 - filtering of summary list based on user roles

- app/models/PageReview.scala
- app/services/ReviewService.scala
- it/data/ExamplePayloads.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/data/ReviewData.scala
- test/services/ReviewServiceSpec.scala
Adding page result to data returned to manage
> Page review Status - merge before EG-808

- app/controllers/ApprovalController.scala
- app/controllers/ProcessReviewController.scala
- app/models/errors/Error.scala
- app/repositories/ApprovalRepository.scala
- app/repositories/PublishedRepository.scala
- app/repositories/repositories.scala
- app/services/ApprovalService.scala
- app/services/PublishedService.scala
- app/services/ReviewService.scala
- test/controllers/ApprovalControllerSpec.scala
- test/controllers/ProcessReviewControllerSpec.scala
- test/services/ApprovalServiceSpec.scala
- test/services/PublishedServiceSpec.scala
- test/services/ReviewServiceSpec.scala
Run with associated branch in manage - this can be merged before manage
> EG-989 - Duplicate Process Code

- app/services/PageBuilder.scala
- test/models/ocelot/ProcessJson.scala
- test/services/PageBuilderSpec.scala
reordered json to make it easier to add entries / follow
Added @tailrec based on intellij highlighting
> EG-FIX Create a review entry for the outcome page for the admin tool 

- app/models/ocelot/stanzas/InputStanza.scala
- test/models/ocelot/stanzas/InputStanzaSpec.scala
- test/services/PageBuilderSpec.scala
- test/utils/StanzaHelper.scala
Includes sync with viewer
Use in combination with viewer EG-1208-Number-Input branch
> EG-1207 - Number input

- app/controllers/ApprovalController.scala
- app/controllers/ProcessReviewController.scala
- app/controllers/PublishedController.scala
- app/controllers/ScratchController.scala
- app/core/models/ocelot/stanzas/ValueStanza.scala
- app/core/services/PageBuilder.scala
- app/core/services/ProcessPopulation.scala
- app/testOnly/controllers/ApprovalController.scala
- app/testOnly/controllers/PublishedController.scala
- app/testOnly/controllers/ScratchController.scala
- conf/application.conf
- it/data/ExamplePayloads.scala
- it/endpoints/GetApprovalProcessISpec.scala
- it/endpoints/GetProcessReviewISpec.scala
- it/endpoints/GetPublishedProcessISpec.scala
- it/endpoints/GetScratchProcessISpec.scala
- it/endpoints/PostApprovalProcessISpec.scala
- it/endpoints/PostProcessReviewISpec.scala
- it/endpoints/PostScratchProcessISpec.scala
- it/stubs/AuditStub.scala
- it/stubs/AuthStub.scala
- it/support/IntegrationSpec.scala
- it/support/WireMockHelper.scala
- it/support/WireMockMethods.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/core/models/ocelot/stanzas/CalculationStanzaSpec.scala
- test/core/models/ocelot/stanzas/ChoiceStanzaSpec.scala
- test/mocks/MockHttpClient.scala
Play 27 upgrade 
Issue with Seq and :: in match statement
Some file headers were updated for the copyright year change
> EG-1196 play 27

- app/core/models/ocelot/LabelCache.scala
- test/base/BaseSpec.scala
- test/core/models/StanzaHelper.scala
- test/core/models/ocelot/LabelSpec.scala
- test/core/models/ocelot/ProcessSpec.scala
- test/core/services/PageBuilderSpec.scala
Synchronisation with EG-1296 Viewer changes
> EG-1297 Updates tests for sequence renderer functionality

- app/core/models/ocelot/Flow.scala
- app/core/models/ocelot/LabelCache.scala
- app/core/models/ocelot/stanzas/SequenceStanza.scala
- app/core/services/package.scala
- app/repositories/ArchiveRepository.scala
- app/repositories/PublishedRepository.scala
- build.sbt
- conf/application-json-logger.xml
- scalastyle-config.xml
- test/controllers/PublishedControllerSpec.scala
- test/core/models/ocelot/FlowSpec.scala
- test/core/models/ocelot/LabelSpec.scala
- test/core/models/ocelot/stanzas/SequenceStanzaSpec.scala
- test/services/PublishedServiceSpec.scala
Also added application logger to application-json.logger.xml and resolved compilations warnings introduced on ticket EG-1334
> EG-1438, synced EG-1436 changes from viewer.

- app/controllers/actions/PrivilegedAction.scala
- build.sbt
- conf/prod.routes
- project/AppDependencies.scala
- project/CodeCoverageSettings.scala
- project/build.properties
- project/plugins.sbt
- test/core/services/PageBuilderErrorsSpec.scala
- test/services/ProcessFinalisationServiceSpec.scala
Dependecies updated
compilation errors fixed
> Dl 12499 - Play 3.0 Upgrade

- app/core/services/PageBuilder.scala
- app/repositories/ApprovalProcessReviewRepository.scala
- app/services/ReviewService.scala
- app/services/ValidatingPageBuilder.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/core/models/ocelot/stanzas/CalculationStanzaSpec.scala
- test/core/models/ocelot/stanzas/ChoiceStanzaSpec.scala
- test/core/models/ocelot/stanzas/InstructionSpec.scala
- test/core/models/ocelot/stanzas/InstructionStanzaSpec.scala
- test/core/models/ocelot/stanzas/PageStanzaSpec.scala
- test/core/models/ocelot/stanzas/QuestionStanzaSpec.scala
- test/core/models/ocelot/stanzas/RowStanzaSpec.scala
- test/core/models/ocelot/stanzas/StanzaRenderingSpec.scala
- test/core/models/ocelot/stanzas/StanzaSpec.scala
- test/core/services/GraphPageBuilderSpec.scala
- test/core/services/PageBuilderErrorsSpec.scala
- test/core/services/PageBuilderSpec.scala
- test/mocks/MockApprovalProcessReviewRepository.scala
- test/services/ReviewServiceSpec.scala
- test/services/ValidatingPageBuilderErrorsSpec.scala
- test/services/ValidatingPageBuilderSpec.scala
DL-13412 - when an approval process is published, the related approvalProcessReviews record is deleted. This change includes new unit tests, and updated dependencies.
> DL 13412 - deletion of approvalProcessReviews record when publishing

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> DL-14995, Dependency Updates
